リモートリポジトリの変更

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -51,12 +51,13 @@ RUN composer clear-cache && \
 RUN test -f /var/www/.env || { echo ".env file is missing"; exit 1; }
 
 # Laravelのキー生成とキャッシュクリアを実行
+# ここではマイグレーションを実行しないようにする
 RUN php artisan key:generate || { echo "key:generate failed"; exit 1; } && \
     php artisan config:cache || { echo "config:cache failed"; exit 1; } && \
-    php artisan view:cache || { echo "view:cache failed"; exit 1; } && \
-    php artisan migrate || { echo "migrate failed"; exit 1; }
+    php artisan view:cache || { echo "view:cache failed"; exit 1; }
+
 # ポートを開放
-EXPOSE ${PORT:-80}
+EXPOSE 9000
 
 # PHP-FPMの起動
 CMD ["php-fpm"]
